version: '3.5'
services:
  na-client-bot:
    image: docker.pkg.github.com/news-aggregator-bot/artifactory/bepicky.na-client-client
    environment:
      - TG_CLIENT_TOKEN=${TG_CLIENT_TOKEN}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - 8070:8080
#  na-admin-bot:
#    image: docker.pkg.github.com/news-aggregator-bot/artifactory/bepicky.na-bot-admin
#    environment:
#      - TG_CLIENT_TOKEN=${TG_CLIENT_TOKEN}
#      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
#    ports:
#      - 8075:8080
networks:
  default:
    external:
      name: picky

